default: &default
  adapter: postgresql
  encoding: unicode
  username:
  password:                   
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: test_project_development

test:
  <<: *default
  database: test_project_test

production:
  <<: *default
  database: test_project_production
  username: test_project
  password: <%= ENV["TEST_PROJECT_DATABASE_PASSWORD"] %>
